Day_Calculator/config/routes.rb
Rails.application.routes.draw do
  resources :personages

  root "personages#index"

end

Day_Calculator/app/models/personage.rb
class Personage < ActiveRecord::Base
end

Day_Calculator/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Day_Calculator/app/controllers/personages_controller.rb
class PersonagesController < ApplicationController
  before_action :set_personage, only: [:show, :edit, :update, :destroy]
  # GET /personages
  # GET /personages.json





  def index
    @personages = Personage.all
  end

  # GET /personages/1
  # GET /personages/1.json
  def show
  end

  # GET /personages/new
  def new
    @personage = Personage.new
  end

  # GET /personages/1/edit
  def edit
  end

  # POST /personages
  # POST /personages.json
  def create
    @personage = Personage.new(personage_params)

    @personage.daysalive = (Date.today() - @personage.birthday)
    @personage.martian = ((Date.today()-@personage.birthday)*0.97)

    respond_to do |format|
      if @personage.save
        format.html { redirect_to @personage, notice: 'Personage was successfully created.' }
        format.json { render :show, status: :created, location: @personage }
      else
        format.html { render :new }
        format.json { render json: @personage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personages/1
  # PATCH/PUT /personages/1.json
  def update
    respond_to do |format|
      if @personage.update(personage_params)
        format.html { redirect_to @personage, notice: 'Personage was successfully updated.' }
        format.json { render :show, status: :ok, location: @personage }
      else
        format.html { render :edit }
        format.json { render json: @personage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personages/1
  # DELETE /personages/1.json
  def destroy
    @personage.destroy
    respond_to do |format|
      format.html { redirect_to personages_url, notice: 'Personage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personage
      @personage = Personage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personage_params
      params.require(:personage).permit(:name, :lastname, :birthday, :daysalive)
    end
end

Day_Calculator/app/helpers/application_helper.rb
module ApplicationHelper
end

Day_Calculator/app/helpers/personages_helper.rb
module PersonagesHelper
end

Day_Calculator/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DayCalc3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Day_Calculator/app/views/personages/_form.html.erb
<%= form_for(@personage) do |f| %>
  <% if @personage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@personage.errors.count, "error") %> prohibited this personage from being saved:</h2>

      <ul>
      <% @personage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :First_name %><br>
    <%= f.text_field :name %>
  </div>

    <div class="field">
      <%= f.label :Last_name %><br>
      <%= f.text_field :lastname %>
    </div>

  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday, :order => [:day, :month, :year], :start_year=>1900,:end_year=>2015 %>
  </div>

  <div class="actions">
    <%= f.submit  "Create"%>
  </div>
<% end %>

Day_Calculator/app/views/personages/edit.html.erb
<h1>Editing Personage</h1>

<%= render 'form' %>

<%= link_to 'Show', @personage %> |
<%= link_to 'Back', personages_path %>

Day_Calculator/app/views/personages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Personages</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Birthday</th>
      <th>Daysalive</th>
      <th>Martian</th>
      <th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personages.each do |personage| %>
      <tr>
        <td><%= personage.name %></td>
        <td><%= personage.lastname %></td>
        <td><%= personage.birthday %></td>
        <td><%= personage.daysalive %></td>
        <td><%= personage.martian %></td>
        <td><%= personage.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create', new_personage_path %>

Day_Calculator/app/views/personages/new.html.erb
<h1>New Personage</h1>

<%= render 'form' %>

<%= link_to 'Back', personages_path %>

Day_Calculator/app/views/personages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First Name:</strong>
  <%= @personage.name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @personage.lastname %>
</p>


<p>
  <strong>Birthday:</strong>
  <%= @personage.birthday %>
</p>

<p>
  <strong>Daysalive:</strong>
  <%= @personage.daysalive %>
</p>


<p>
  <strong>Martian days:</strong>
  <%= @personage.martian %>
</p>

<%= link_to 'Edit', edit_personage_path(@personage) %> |
<%= link_to 'Back', personages_path %>